[package]
name = "kt_common"

version.workspace = true
edition.workspace = true

[dependencies]
bevy.workspace = true
bevy-inspector-egui.workspace = true
rand.workspace = true
bevy_prototype_lyon.workspace = true
bevy_ecs_ldtk.workspace = true
bevy_rapier2d.workspace = true
